"""HSE2 container model helpers."""

from .combined_kdf import (
    HSE2_COMBINED_KDF_CONTEXT,
    CombinedKDFResult,
    derive_kek_from_password_and_keyfile,
)
from .container_codec import (
    HSE2_HEADER_ENCODING_CANONICAL_JSON,
    HSE2_MAGIC,
    HSE2_PREAMBLE_SIZE,
    HSE2_PREAMBLE_VERSION,
    HSE2Preamble,
    decode_header_frame,
    encode_header_frame,
    hse2_header_from_dict,
)
from .dpapi import dpapi_protect_bytes, dpapi_unprotect_bytes, is_dpapi_available
from .encoding import b64decode_bytes, b64encode_bytes
from .header_auth import (
    attach_header_auth_tag,
    compute_header_auth_tag,
    require_valid_header_auth_tag,
    verify_header_auth_tag,
)
from .keyfile_kdf import (
    HSE2_KEYFILE_CONTEXT,
    HSE2_KEYFILE_MIN_SIZE,
    KeyfileKDFResult,
    derive_kek_from_keyfile,
    validate_keyfile_bytes,
)
from .keys import (
    HSE2_KEY_SIZE,
    HSE2KeyMaterial,
    generate_dek,
    generate_kek,
    generate_key_material,
    generate_mek,
    validate_key_bytes,
)
from .manifest_crypto import (
    EncryptedManifest,
    decrypt_manifest,
    encrypt_manifest,
    encrypted_manifest_from_dict,
)
from .models import (
    CipherSuite,
    HSE2Header,
    HSE2ModelError,
    KDFProfile,
    ManifestPolicy,
    PayloadLayout,
    WrappedKeys,
    WrapperRecord,
    canonical_json_bytes,
    get_kdf_profile,
)
from .password_kdf import (
    HSE2_KDF_SALT_SIZE,
    PasswordKDFResult,
    derive_kek_from_password,
    normalize_password,
)
from .payload_crypto import (
    EncryptedPayloadChunk,
    decrypt_payload_chunk,
    encrypt_payload_chunk,
    encrypted_payload_chunk_from_dict,
)
from .wrapper_builders import (
    BuiltWrapper,
    UnwrappedContentKeys,
    build_dpapi_wrapper,
    build_keyfile_wrapper,
    build_password_keyfile_wrapper,
    build_password_wrapper,
    build_wrapper_from_kek,
    unwrap_dpapi_wrapper,
    unwrap_keyfile_wrapper,
    unwrap_password_keyfile_wrapper,
    unwrap_password_wrapper,
    unwrap_wrapper_with_kek,
)
from .wrapper_serialization import (
    WrappedKeyPairBlobs,
    build_wrapper_record,
    wrapped_blob_from_metadata,
    wrapped_blob_to_metadata,
)
from .wrapping import (
    HSE2_WRAP_AUTH_TAG_SIZE,
    HSE2_WRAP_NONCE_SIZE,
    WrappedKeyBlob,
    key_confirmation_tag,
    unwrap_key_material,
    wrap_key_material,
)

__all__ = [
    "BuiltWrapper",
    "CipherSuite",
    "CombinedKDFResult",
    "EncryptedManifest",
    "EncryptedPayloadChunk",
    "HSE2Header",
    "HSE2ModelError",
    "HSE2KeyMaterial",
    "HSE2Preamble",
    "HSE2_COMBINED_KDF_CONTEXT",
    "HSE2_HEADER_ENCODING_CANONICAL_JSON",
    "HSE2_KEYFILE_CONTEXT",
    "HSE2_KEYFILE_MIN_SIZE",
    "HSE2_KEY_SIZE",
    "HSE2_KDF_SALT_SIZE",
    "HSE2_MAGIC",
    "HSE2_PREAMBLE_SIZE",
    "HSE2_PREAMBLE_VERSION",
    "HSE2_WRAP_AUTH_TAG_SIZE",
    "HSE2_WRAP_NONCE_SIZE",
    "KDFProfile",
    "KeyfileKDFResult",
    "ManifestPolicy",
    "PasswordKDFResult",
    "PayloadLayout",
    "UnwrappedContentKeys",
    "WrappedKeyBlob",
    "WrappedKeyPairBlobs",
    "WrappedKeys",
    "WrapperRecord",
    "attach_header_auth_tag",
    "b64decode_bytes",
    "b64encode_bytes",
    "build_dpapi_wrapper",
    "build_keyfile_wrapper",
    "build_password_keyfile_wrapper",
    "build_password_wrapper",
    "build_wrapper_from_kek",
    "build_wrapper_record",
    "canonical_json_bytes",
    "compute_header_auth_tag",
    "decode_header_frame",
    "decrypt_manifest",
    "decrypt_payload_chunk",
    "derive_kek_from_keyfile",
    "derive_kek_from_password",
    "derive_kek_from_password_and_keyfile",
    "dpapi_protect_bytes",
    "dpapi_unprotect_bytes",
    "encode_header_frame",
    "encrypt_manifest",
    "encrypt_payload_chunk",
    "encrypted_manifest_from_dict",
    "encrypted_payload_chunk_from_dict",
    "generate_dek",
    "generate_kek",
    "generate_key_material",
    "generate_mek",
    "get_kdf_profile",
    "hse2_header_from_dict",
    "is_dpapi_available",
    "key_confirmation_tag",
    "normalize_password",
    "require_valid_header_auth_tag",
    "unwrap_dpapi_wrapper",
    "unwrap_key_material",
    "unwrap_keyfile_wrapper",
    "unwrap_password_keyfile_wrapper",
    "unwrap_password_wrapper",
    "unwrap_wrapper_with_kek",
    "validate_key_bytes",
    "validate_keyfile_bytes",
    "verify_header_auth_tag",
    "wrap_key_material",
    "wrapped_blob_from_metadata",
    "wrapped_blob_to_metadata",
]
