"""Constants for the HSE2 container format."""

from __future__ import annotations

HSE2_MAGIC = b"HSE2"
HSE2_VERSION = 2

AES_256_KEY_BYTES = 32
GCM_NONCE_BYTES = 12
HSE2_KEY_MATERIAL_BYTES = 64

DEFAULT_CHUNK_SIZE = 1024 * 1024

PROFILE_COMPATIBLE = "compatible"
PROFILE_HARDENED = "hardened"
PROFILE_PARANOID = "paranoid"

SUPPORTED_KDF_ALGORITHM = "argon2id"
DEFAULT_WRAP_CIPHER = "AES-256-GCM"
DEFAULT_PAYLOAD_CIPHER = "AES-256-GCM"
DEFAULT_MANIFEST_CIPHER = "AES-256-GCM"
